# Generated by Django 4.0.4 on 2022-04-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Jop_type',
            field=models.CharField(choices=[('Full time', 'Full Time'), ('Part time', 'Part Time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
