# Generated by Django 4.0.4 on 2022-04-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0002_job_jop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Job_description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
