# Generated by Django 4.0.4 on 2022-04-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0003_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='Salary',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='Vacancy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='excperience',
            field=models.IntegerField(default=1),
        ),
    ]
